flask-mysql-zappa-lambda/application/__init__.py
"""Initialize Flask app.

Returns:
    Flask app.
"""
from flask import Flask, g
from application.views.frontend import bp_frontend
from application.views.api import bp_api
from os import environ, path
from werkzeug.middleware.proxy_fix import ProxyFix
from dotenv import load_dotenv


app = Flask(
    __name__,
    static_url_path='/static',
    static_folder='static',
    instance_relative_config=False
)

if path.exists(".env"):
    load_dotenv('.env', verbose=True)
    app.logger.debug("Loaded .env")

app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_host=1, x_proto=1)
app.config.from_object('config.Config')
app.register_blueprint(bp_frontend)
app.register_blueprint(bp_api, url_prefix='/api')


@app.before_request
def app_before_request():
    """Set up g variables that will be useful for all requests."""
    for key in environ.keys():
        if not key.startswith('FLASK_G_'):
            continue
        _key = key.lower().replace('flask_g_', '')
        setattr(g, _key, environ.get(key))
        app.logger.debug(f"Setting g.{_key}={g.get(_key)}")

flask-mysql-zappa-lambda/application/modules/__init__.py
"""Custom modules."""

flask-mysql-zappa-lambda/application/views/api.py
"""Build API routes."""
from flask import jsonify, Blueprint, request, url_for

bp_api = Blueprint('api', __name__)


@bp_api.route('/sup_world', methods=['GET'])
def sup_world():
    """Return JSON from a database."""
    from application.modules.db import DB
    db = DB()
    result = db.select_one("select * from skeleton")
    return jsonify(result)


@bp_api.route('/url_test', methods=['GET'])
def url_test():
    """Test URLs returned by Flask.

    Returns:
        string: JSON document of different URLs and paths
    """
    return jsonify({
        'base_url': request.base_url,
        'url_rule': str(request.url_rule),
        'request_path': request.path,
        'request_url': request.url,
        'request_host': request.host,
        'request_host_url': request.host_url,
        'host_header': request.headers.get('X-Forwarded-Host'),
        'url_for': url_for('api.url_test')
    })

flask-mysql-zappa-lambda/application/views/frontend.py
"""Build front end routes."""
from flask import render_template, Blueprint


bp_frontend = Blueprint('frontend', __name__, template_folder='templates')


@bp_frontend.route('/', methods=['GET'])
def index():
    """Index."""
    return render_template('index.html')

flask-mysql-zappa-lambda/application/templates/index.html
{% extends "wrapper.html" %}

{% block head_extra %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/application.css').replace('/prod', '') }}">
{% endblock %}

{% block body_extra %}
<scrpt src="{{ url_for('static', filename='js/application.js').replace('/prod', '') }}">

<script>
    $.get("{{ url_for('api.sup_world') }}", function (data) {
        $('#heading').text(data.msg);
    });
</script>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h1 id='heading'></h1>
        </div>
    </div>
</div>
{% endblock %}

flask-mysql-zappa-lambda/application/templates/wrapper.html
<!doctype html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}{{g.app_name}}</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Site icons -->
        <link rel="shortcut icon" type="image/jpg" href="{{ url_for('static', filename='favicon.ico') }}"/>
        <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='apple-touch-icon.png') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon-32x32.png') }}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon-16x16.png') }}">
        <!--link rel="manifest" href="{{ url_for('static', filename='site.webmanifest') }}"-->
        <link rel="mask-icon" href="{{ url_for('static', filename='safari-pinned-tab.svg') }}" color="#1b2837">
        <meta name="msapplication-TileColor" content="#1b2837">
        <meta name="theme-color" content="#1b2837">
        
        {%- filter indent(width=8) %}
        {%- block socialgraph %}
        <!-- OpenGraph Social Preview stuff-->
        <meta property="og:type" content="website" />
        <meta property="og:title" content="{{g.app_name}}" />
        <meta property="og:description" content="{{g.app_description}}" />
        <meta property="og:url" content="{{g.base_url}}" />
        <meta property="og:site_name" content="{{g.app_name}}" />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:description" content="{{g.app_description}}" />
        <meta name="twitter:title" content="{{g.app_name}}" />

        <meta property="og:image" content="{{ url_for('static', filename='social_preview.jpg') }}" />
        <meta name="twitter:image" content="{{ url_for('static', filename='social_preview.jpg') }}" />
        {% endblock %}
        {% endfilter %}

        {%- if g.bootstrap_version %}
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@{{g.bootstrap_version}}/dist/css/bootstrap.min.css" rel="stylesheet">
        {% endif %}

        {%- if g.fontawesome_version %}

        <!-- Font awesome -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@{{g.fontawesome_version}}/css/all.min.css"/>

        {% endif %}

        {%- if g.ga_tag %}

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id={{g.ga_tag}}"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', '{{g.ga_tag}}');
        </script>

        {% endif %}

        {%- filter indent(width=8) %}

        {%- block head_extra %}
        {% endblock %}

        {% endfilter %}
    </head>

    {% filter indent(width=4) %}
    <body>

    {% block body %}
    {% endblock %}

    {%- if g.jquery_version %}
    <script src="https://code.jquery.com/jquery-{{g.jquery_version}}.min.js"></script>
    {% endif %}

    {%- if g.bootstrap_version %}
    <!-- Bootstrap JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@{{g.bootstrap_version}}/dist/js/bootstrap.bundle.min.js"></script>
    {% endif %}    

    {% block body_extra %}
    {% endblock %}

    </body>
    {% endfilter %}
</html>